// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaPVD8aca3dbAsZiOmKodLxgSvD2dU_sw',
    appId: '1:784896842653:web:ad4c1ee50f0dffd7416d74',
    messagingSenderId: '784896842653',
    projectId: 'phonediary-6b88a',
    authDomain: 'phonediary-6b88a.firebaseapp.com',
    databaseURL: 'https://phonediary-6b88a-default-rtdb.firebaseio.com',
    storageBucket: 'phonediary-6b88a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAker18Oy03rIVlNpExtK40zhstxM8XpYQ',
    appId: '1:784896842653:android:e99ff642ecf3f9db416d74',
    messagingSenderId: '784896842653',
    projectId: 'phonediary-6b88a',
    databaseURL: 'https://phonediary-6b88a-default-rtdb.firebaseio.com',
    storageBucket: 'phonediary-6b88a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_elj9qfSJL04672HpyBz7ZMdtE6Ncsoo',
    appId: '1:784896842653:ios:2a4b10e8196dea60416d74',
    messagingSenderId: '784896842653',
    projectId: 'phonediary-6b88a',
    databaseURL: 'https://phonediary-6b88a-default-rtdb.firebaseio.com',
    storageBucket: 'phonediary-6b88a.appspot.com',
    iosClientId: '784896842653-2opp2o3pg32p7991idgcn1c6evhhr89e.apps.googleusercontent.com',
    iosBundleId: 'com.example.phonediary',
  );
}
